import type {
  User,
  AnnotationTask,
  Annotation,
  QAReview,
  WorkforceMember,
  WorkforceTrainingModule,
  WorkforceTrainingSummary,
  WorkforceAlert,
  WorkforceCompositionSlice,
  WorkforceHeadcountTrendPoint,
  WorkforceMemberPersonalSummary,
} from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    email: "admin@sentra.com",
    name: "Alex Admin",
    role: "admin",
  },
  {
    id: "2",
    email: "annotator1@sentra.com",
    name: "Sarah Annotator",
    role: "annotator",
  },
  {
    id: "3",
    email: "annotator2@sentra.com",
    name: "John Annotator",
    role: "annotator",
  },
  {
    id: "6",
    email: "lead@sentra.com",
    name: "Priya Team Lead",
    role: "team_lead",
  },
  {
    id: "4",
    email: "qa@sentra.com",
    name: "Emma QA",
    role: "qa",
  },
  {
    id: "5",
    email: "client@sentra.com",
    name: "Mike Client",
    role: "client",
  },
]

export const mockTasks: AnnotationTask[] = [
  {
    id: "1",
    title: "Product Images - Batch A",
    type: "image",
    status: "in_progress",
    priority: "high",
    assignedTo: "2",
    createdAt: new Date("2025-10-20"),
    dueDate: new Date("2025-11-15"),
  },
  {
    id: "2",
    title: "Customer Reviews Sentiment",
    type: "text",
    status: "pending",
    priority: "medium",
    assignedTo: "3",
    createdAt: new Date("2025-10-22"),
    dueDate: new Date("2025-11-10"),
  },
  {
    id: "3",
    title: "Medical Report Classification",
    type: "text",
    status: "completed",
    priority: "high",
    assignedTo: "2",
    createdAt: new Date("2025-10-15"),
    dueDate: new Date("2025-11-05"),
  },
  {
    id: "4",
    title: "Vehicle Detection - Highway Footage",
    type: "image",
    status: "completed",
    priority: "high",
    assignedTo: "3",
    createdAt: new Date("2025-10-18"),
    dueDate: new Date("2025-11-08"),
  },
  {
    id: "5",
    title: "E-commerce Product Tags",
    type: "text",
    status: "pending",
    priority: "low",
    assignedTo: "2",
    createdAt: new Date("2025-10-25"),
    dueDate: new Date("2025-11-20"),
  },
  {
    id: "6",
    title: "Retail Store Images - Merchandise",
    type: "image",
    status: "in_progress",
    priority: "medium",
    assignedTo: "3",
    createdAt: new Date("2025-10-21"),
    dueDate: new Date("2025-11-18"),
  },
  {
    id: "7",
    title: "Technical Support Tickets - Classification",
    type: "text",
    status: "pending",
    priority: "high",
    assignedTo: "2",
    createdAt: new Date("2025-10-26"),
    dueDate: new Date("2025-11-12"),
  },
  {
    id: "8",
    title: "Traffic Jam Detection - City Streets",
    type: "video",
    status: "pending",
    priority: "high",
    assignedTo: "3",
    createdAt: new Date("2025-10-27"),
    dueDate: new Date("2025-11-14"),
  },
  {
    id: "9",
    title: "Wildlife Behavior Analysis",
    type: "video",
    status: "in_progress",
    priority: "medium",
    assignedTo: "2",
    createdAt: new Date("2025-10-28"),
    dueDate: new Date("2025-11-22"),
  },
]

export const mockAnnotations: Annotation[] = [
  {
    id: "1",
    taskId: "1",
    type: "bbox",
    data: { x: 100, y: 100, width: 200, height: 150, label: "product" },
    createdAt: new Date("2025-10-28"),
    status: "approved",
  },
  {
    id: "2",
    taskId: "1",
    type: "bbox",
    data: { x: 350, y: 80, width: 180, height: 200, label: "product" },
    createdAt: new Date("2025-10-28"),
    status: "pending",
  },
  {
    id: "3",
    taskId: "2",
    type: "highlight",
    data: { text: "amazing product", sentiment: "positive" },
    createdAt: new Date("2025-10-29"),
    status: "approved",
  },
  {
    id: "4",
    taskId: "2",
    type: "highlight",
    data: { text: "terrible experience", sentiment: "negative" },
    createdAt: new Date("2025-10-29"),
    status: "approved",
  },
  {
    id: "5",
    taskId: "3",
    type: "highlight",
    data: { text: "diagnosis: pneumonia", category: "diagnosis" },
    createdAt: new Date("2025-10-27"),
    status: "approved",
  },
]

export const mockQAReviews: QAReview[] = [
  {
    id: "1",
    annotationId: "1",
    reviewerId: "4",
    score: 95,
    comment: "Excellent bounding box placement and labeling",
    status: "approved",
    createdAt: new Date("2025-10-28"),
  },
  {
    id: "2",
    annotationId: "3",
    reviewerId: "4",
    score: 88,
    comment: "Good sentiment classification, minor context issue",
    status: "approved",
    createdAt: new Date("2025-10-29"),
  },
  {
    id: "3",
    annotationId: "4",
    reviewerId: "4",
    score: 92,
    comment: "Accurate sentiment identification",
    status: "approved",
    createdAt: new Date("2025-10-29"),
  },
  {
    id: "4",
    annotationId: "2",
    reviewerId: "4",
    score: 78,
    comment: "Box too small, needs adjustment",
    status: "needs_revision",
    createdAt: new Date("2025-10-28"),
  },
  {
    id: "5",
    annotationId: "5",
    reviewerId: "4",
    score: 96,
    comment: "Perfect medical report classification",
    status: "approved",
    createdAt: new Date("2025-10-27"),
  },
]

export const mockAnnotatorStats = {
  totalAnnotators: 42,
  activeToday: 28,
  tasksCompleted: 1247,
  averageQualityScore: 92.3,
  onTimeDelivery: 98.5,
}

export const mockProjectStats = {
  activeProjects: 12,
  totalAnnotations: 8934,
  annotationsCompleted: 7123,
  averageAccuracy: 94.2,
  totalWorkforceCost: 14230,
}

export const mockWorkforceMembers: WorkforceMember[] = [
  {
    id: "2",
    email: "annotator1@sentra.com",
    name: "Sarah Annotator",
    role: "annotator",
    status: "active",
    location: "Austin, USA",
    timezone: "GMT-5",
    joinDate: new Date("2024-06-12"),
    tasksAssigned: 18,
    tasksInQueue: 6,
    completedThisWeek: 42,
    qualityScore: 95,
    qualityTrend: 3.2,
    trainingCompletion: 100,
    specializations: ["Retail", "E-commerce"],
    certifications: ["Annotation Fundamentals", "Retail Taxonomy"],
  },
  {
    id: "3",
    email: "annotator2@sentra.com",
    name: "John Annotator",
    role: "annotator",
    status: "active",
    location: "London, UK",
    timezone: "GMT+0",
    joinDate: new Date("2024-03-04"),
    tasksAssigned: 15,
    tasksInQueue: 9,
    completedThisWeek: 36,
    qualityScore: 90,
    qualityTrend: -1.1,
    trainingCompletion: 80,
    specializations: ["Computer Vision"],
    certifications: ["Advanced Bounding Boxes"],
  },
  {
    id: "7",
    email: "annotator3@sentra.com",
    name: "Lucía Annotator",
    role: "annotator",
    status: "training",
    location: "Madrid, Spain",
    timezone: "GMT+1",
    joinDate: new Date("2025-01-15"),
    tasksAssigned: 6,
    tasksInQueue: 12,
    completedThisWeek: 14,
    qualityScore: 87,
    qualityTrend: 2.6,
    trainingCompletion: 65,
    specializations: ["Healthcare"],
    certifications: ["HIPAA Basics"],
  },
  {
    id: "8",
    email: "annotator4@sentra.com",
    name: "Noah Annotator",
    role: "annotator",
    status: "inactive",
    location: "Toronto, Canada",
    timezone: "GMT-4",
    joinDate: new Date("2023-11-01"),
    tasksAssigned: 0,
    tasksInQueue: 0,
    completedThisWeek: 0,
    qualityScore: 0,
    qualityTrend: 0,
    trainingCompletion: 45,
    specializations: ["Document Annotation"],
    certifications: ["Annotation Fundamentals"],
    upcomingPtoDays: 5,
  },
  {
    id: "4",
    email: "qa@sentra.com",
    name: "Emma QA",
    role: "qa",
    status: "active",
    location: "Austin, USA",
    timezone: "GMT-5",
    joinDate: new Date("2023-09-22"),
    tasksAssigned: 10,
    tasksInQueue: 4,
    completedThisWeek: 28,
    qualityScore: 98,
    qualityTrend: 1.4,
    trainingCompletion: 100,
    specializations: ["Quality Assurance"],
    certifications: ["QA Certification"],
  },
  {
    id: "6",
    email: "lead@sentra.com",
    name: "Priya Team Lead",
    role: "team_lead",
    status: "active",
    location: "Bengaluru, India",
    timezone: "GMT+5.5",
    joinDate: new Date("2022-12-08"),
    tasksAssigned: 22,
    tasksInQueue: 3,
    completedThisWeek: 18,
    qualityScore: 93,
    qualityTrend: 0.8,
    trainingCompletion: 100,
    specializations: ["Team Management", "Policy"],
    certifications: ["Leadership"],
    upcomingPtoDays: 2,
  },
]

export const mockWorkforceAlerts: WorkforceAlert[] = [
  {
    id: "alert-1",
    title: "High priority QA backlog",
    description: "12 tasks waiting for QA review for more than 48 hours",
    priority: "high",
    owners: ["4"],
    action: "Review backlog",
  },
  {
    id: "alert-2",
    title: "Training overdue",
    description: "3 annotators have not completed Quality Standards module",
    priority: "medium",
    owners: ["6"],
    action: "Send reminder",
    dueDate: new Date("2025-11-08"),
  },
  {
    id: "alert-3",
    title: "Upcoming PTO",
    description: "Noah Annotator requested PTO next week (5 days)",
    priority: "low",
    owners: ["6"],
    action: "Adjust coverage",
    dueDate: new Date("2025-11-10"),
  },
]

export const mockWorkforceTrainingModules: WorkforceTrainingModule[] = [
  {
    id: "training-1",
    name: "Annotation Basics",
    completion: 100,
    status: "completed",
    participants: 38,
    averageScore: 94,
  },
  {
    id: "training-2",
    name: "Advanced Labeling",
    completion: 78,
    status: "in_progress",
    participants: 24,
    averageScore: 88,
    dueDate: new Date("2025-11-20"),
  },
  {
    id: "training-3",
    name: "Quality Standards",
    completion: 42,
    status: "pending",
    participants: 17,
    averageScore: 0,
    dueDate: new Date("2025-11-18"),
  },
  {
    id: "training-4",
    name: "Tool Mastery",
    completion: 100,
    status: "completed",
    participants: 32,
    averageScore: 97,
  },
  {
    id: "training-5",
    name: "Domain Expertise",
    completion: 61,
    status: "in_progress",
    participants: 21,
    averageScore: 86,
    dueDate: new Date("2025-11-25"),
  },
]

export const mockWorkforceTrainingSummary: WorkforceTrainingSummary = {
  completionRate: 76,
  certifiedCount: 29,
  inProgressCount: 9,
  overdueCount: 3,
  nextEvaluationDate: new Date("2025-11-21"),
}

export const mockWorkforceComposition: WorkforceCompositionSlice[] = [
  { name: "Annotators", value: 35, change: 4 },
  { name: "QA Reviewers", value: 10, change: 1 },
  { name: "Team Leads", value: 5, change: 0 },
  { name: "Admins", value: 2, change: 0 },
]

export const mockWorkforceHeadcountTrend: WorkforceHeadcountTrendPoint[] = [
  { month: "Jun", annotators: 26, qa: 7, teamLeads: 4, contractors: 5 },
  { month: "Jul", annotators: 28, qa: 8, teamLeads: 4, contractors: 6 },
  { month: "Aug", annotators: 30, qa: 9, teamLeads: 5, contractors: 6 },
  { month: "Sep", annotators: 33, qa: 9, teamLeads: 5, contractors: 7 },
  { month: "Oct", annotators: 35, qa: 10, teamLeads: 5, contractors: 8 },
  { month: "Nov", annotators: 36, qa: 10, teamLeads: 5, contractors: 8 },
]

export const mockWorkforcePersonalSummaries: WorkforceMemberPersonalSummary[] = [
  {
    memberId: "2",
    activeTasks: 6,
    dueToday: 2,
    avgQuality: 95,
    trainingModulesDue: 0,
    focusAreas: ["Retail batch A", "QA rework"],
  },
  {
    memberId: "3",
    activeTasks: 8,
    dueToday: 1,
    avgQuality: 90,
    trainingModulesDue: 1,
    nextTraining: "Quality Standards",
    focusAreas: ["Automotive vision", "Model drift review"],
  },
  {
    memberId: "4",
    activeTasks: 12,
    dueToday: 4,
    avgQuality: 98,
    trainingModulesDue: 0,
    focusAreas: ["QA backlog", "Calibration"],
  },
  {
    memberId: "6",
    activeTasks: 3,
    dueToday: 0,
    avgQuality: 93,
    trainingModulesDue: 0,
    focusAreas: ["Team planning", "Policy refresh"],
  },
]
