import type { User, AnnotationTask, Annotation, QAReview } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    email: "admin@sentra.com",
    name: "Alex Admin",
    role: "admin",
  },
  {
    id: "2",
    email: "annotator1@sentra.com",
    name: "Sarah Annotator",
    role: "annotator",
  },
  {
    id: "3",
    email: "annotator2@sentra.com",
    name: "John Annotator",
    role: "annotator",
  },
  {
    id: "4",
    email: "qa@sentra.com",
    name: "Emma QA",
    role: "qa",
  },
  {
    id: "5",
    email: "client@sentra.com",
    name: "Mike Client",
    role: "client",
  },
]

export const mockTasks: AnnotationTask[] = [
  {
    id: "1",
    title: "Product Images - Batch A",
    type: "image",
    status: "in_progress",
    priority: "high",
    assignedTo: "2",
    createdAt: new Date("2025-10-20"),
    dueDate: new Date("2025-11-15"),
  },
  {
    id: "2",
    title: "Customer Reviews Sentiment",
    type: "text",
    status: "pending",
    priority: "medium",
    assignedTo: "3",
    createdAt: new Date("2025-10-22"),
    dueDate: new Date("2025-11-10"),
  },
  {
    id: "3",
    title: "Medical Report Classification",
    type: "text",
    status: "completed",
    priority: "high",
    assignedTo: "2",
    createdAt: new Date("2025-10-15"),
    dueDate: new Date("2025-11-05"),
  },
  {
    id: "4",
    title: "Vehicle Detection - Highway Footage",
    type: "image",
    status: "completed",
    priority: "high",
    assignedTo: "3",
    createdAt: new Date("2025-10-18"),
    dueDate: new Date("2025-11-08"),
  },
  {
    id: "5",
    title: "E-commerce Product Tags",
    type: "text",
    status: "pending",
    priority: "low",
    assignedTo: "2",
    createdAt: new Date("2025-10-25"),
    dueDate: new Date("2025-11-20"),
  },
  {
    id: "6",
    title: "Retail Store Images - Merchandise",
    type: "image",
    status: "in_progress",
    priority: "medium",
    assignedTo: "3",
    createdAt: new Date("2025-10-21"),
    dueDate: new Date("2025-11-18"),
  },
  {
    id: "7",
    title: "Technical Support Tickets - Classification",
    type: "text",
    status: "pending",
    priority: "high",
    assignedTo: "2",
    createdAt: new Date("2025-10-26"),
    dueDate: new Date("2025-11-12"),
  },
  {
    id: "8",
    title: "Traffic Jam Detection - City Streets",
    type: "video",
    status: "pending",
    priority: "high",
    assignedTo: "3",
    createdAt: new Date("2025-10-27"),
    dueDate: new Date("2025-11-14"),
  },
  {
    id: "9",
    title: "Wildlife Behavior Analysis",
    type: "video",
    status: "in_progress",
    priority: "medium",
    assignedTo: "2",
    createdAt: new Date("2025-10-28"),
    dueDate: new Date("2025-11-22"),
  },
]

export const mockAnnotations: Annotation[] = [
  {
    id: "1",
    taskId: "1",
    type: "bbox",
    data: { x: 100, y: 100, width: 200, height: 150, label: "product" },
    createdAt: new Date("2025-10-28"),
    status: "approved",
  },
  {
    id: "2",
    taskId: "1",
    type: "bbox",
    data: { x: 350, y: 80, width: 180, height: 200, label: "product" },
    createdAt: new Date("2025-10-28"),
    status: "pending",
  },
  {
    id: "3",
    taskId: "2",
    type: "highlight",
    data: { text: "amazing product", sentiment: "positive" },
    createdAt: new Date("2025-10-29"),
    status: "approved",
  },
  {
    id: "4",
    taskId: "2",
    type: "highlight",
    data: { text: "terrible experience", sentiment: "negative" },
    createdAt: new Date("2025-10-29"),
    status: "approved",
  },
  {
    id: "5",
    taskId: "3",
    type: "highlight",
    data: { text: "diagnosis: pneumonia", category: "diagnosis" },
    createdAt: new Date("2025-10-27"),
    status: "approved",
  },
]

export const mockQAReviews: QAReview[] = [
  {
    id: "1",
    annotationId: "1",
    reviewerId: "4",
    score: 95,
    comment: "Excellent bounding box placement and labeling",
    status: "approved",
    createdAt: new Date("2025-10-28"),
  },
  {
    id: "2",
    annotationId: "3",
    reviewerId: "4",
    score: 88,
    comment: "Good sentiment classification, minor context issue",
    status: "approved",
    createdAt: new Date("2025-10-29"),
  },
  {
    id: "3",
    annotationId: "4",
    reviewerId: "4",
    score: 92,
    comment: "Accurate sentiment identification",
    status: "approved",
    createdAt: new Date("2025-10-29"),
  },
  {
    id: "4",
    annotationId: "2",
    reviewerId: "4",
    score: 78,
    comment: "Box too small, needs adjustment",
    status: "needs_revision",
    createdAt: new Date("2025-10-28"),
  },
  {
    id: "5",
    annotationId: "5",
    reviewerId: "4",
    score: 96,
    comment: "Perfect medical report classification",
    status: "approved",
    createdAt: new Date("2025-10-27"),
  },
]

export const mockAnnotatorStats = {
  totalAnnotators: 42,
  activeToday: 28,
  tasksCompleted: 1247,
  averageQualityScore: 92.3,
  onTimeDelivery: 98.5,
}

export const mockProjectStats = {
  activeProjects: 12,
  totalAnnotations: 8934,
  annotationsCompleted: 7123,
  averageAccuracy: 94.2,
  totalWorkforceCost: 14230,
}
